api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            # enabled: false                        # - uncomment untuk mematikan paging secara global
            # page_parameter_name: halaman          # - parameter name for the page (defaultnya page)
            client_enabled: true                    # - memberikan akses pada user/client-
            enabled_parameter_name: pagination      #   untuk setting pagination on/off
            items_per_page: 10                      # - pengaturan jumlah baris data per halaman
            client_items_per_page: true             # - memberikan akses pada user/client-
            items_per_page_parameter_name: limit    #   untuk pengaturan jumlah baris data per halaman
            maximum_items_per_page: 20              #   dengan nama parameter dan batas maksimal tertentu
            partial: true                           # - on/off paging tanpa menghitung total
            client_partial: true                    # - beri akses client on/off paging partial
            partial_parameter_name: partial         # - nama parameter client untuk paging partial